#Enter your main nation, or a name NS Staff would recognize you by as your user agent
user_agent = "DragoE"
regions = ["Warzone Trinidad", "Warzone Tobago"]
#minimum is 100
refresh_rate = 450
#order of urls matters. 1st url associated with 1st region (in multi mode)
webhooks = ["This string should be a url"]
#accepts "single" for single channel opperations,or "multi" for posting different regions in different channels
mode = "single"
#Optional: List of Hex Colour Codes to use for each region. Will default to rainbow if unused
colours = []
